{
    "name": "Force Send Mail",
    "author": "fidobe",
    "category": "other",
    "summary": """Force Send Mail""",
    "license": "AGPL-3",
    "website": "http://www.fidobe.com",
    "description": """Force Send Mail""",
    "version": "17.0.1.0",
    "depends": ["base", "mail"],
    "data": [],
    "assets": {},
    "installable": True,
    "application": True,
    "auto_install": False,
}
